import { describe, expect, it } from "vitest";
import type { EnemyAiRule, EnemyDefinition, StatBlock } from "../../src/content/contracts";
import { ENEMY_DEFINITIONS } from "../../src/content/data/enemies";

type EnemyProjection = Pick<
  EnemyDefinition,
  "id" | "level" | "stats" | "elementWeaknesses" | "elementResistances" | "immunityTags" | "basicSkillId" | "basicTargetStrategy" | "skillIds" | "aiRules"
>;

function stats(maxHp: number, attack: number, defense: number, speed: number, effectHitBps: number, effectResistBps: number): StatBlock {
  return { maxHp, attack, defense, speed, critRateBps: 500, critDamageBps: 15_000, effectHitBps, effectResistBps };
}

function aiRule(
  priority: number,
  conditions: EnemyAiRule["conditions"],
  skillId: string,
  targetStrategy: EnemyAiRule["targetStrategy"],
): EnemyAiRule {
  return { priority, conditions, skillId, targetStrategy, weight: 100 };
}

function projection(enemy: EnemyDefinition): EnemyProjection {
  return {
    id: enemy.id,
    level: enemy.level,
    stats: enemy.stats,
    elementWeaknesses: enemy.elementWeaknesses,
    elementResistances: enemy.elementResistances,
    immunityTags: enemy.immunityTags,
    basicSkillId: enemy.basicSkillId,
    basicTargetStrategy: enemy.basicTargetStrategy,
    skillIds: enemy.skillIds,
    aiRules: enemy.aiRules,
  };
}

const expected: readonly EnemyProjection[] = [
  { id: "enemy_grass_slime", level: 3, stats: stats(300, 42, 18, 45, 0, 0), elementWeaknesses: ["fire"], elementResistances: [], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_defend"], aiRules: [aiRule(80, [{ kind: "selfHpAtMostBps", valueBps: 5000 }], "skill_enemy_defend", "self")] },
  { id: "enemy_thorn_rat", level: 3, stats: stats(255, 44, 15, 60, 0, 0), elementWeaknesses: ["frost"], elementResistances: ["physical"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_double_hit"], aiRules: [aiRule(70, [{ kind: "always" }], "skill_enemy_double_hit", "frontFirstOpponent")] },
  { id: "enemy_fang_wolf", level: 3, stats: stats(405, 50, 18, 36, 0, 0), elementWeaknesses: ["fire"], elementResistances: ["physical"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_bleed_hit"], aiRules: [aiRule(80, [{ kind: "targetMissingStatus", statusId: "status_bleed" }], "skill_enemy_bleed_hit", "frontFirstOpponent"), aiRule(50, [{ kind: "always" }], "skill_enemy_bleed_hit", "frontFirstOpponent")] },
  { id: "enemy_goblin_scout", level: 3, stats: stats(270, 52, 14, 45, 0, 0), elementWeaknesses: ["lightning"], elementResistances: [], immunityTags: [], basicSkillId: "skill_enemy_basic_ranged", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_enemy_slow_hit"], aiRules: [aiRule(80, [{ kind: "targetMissingStatus", statusId: "status_slow" }], "skill_enemy_slow_hit", "lowestHpOpponent")] },
  { id: "enemy_stonehide_boar", level: 3, stats: stats(783, 42, 31, 34, 0, 0), elementWeaknesses: ["poison"], elementResistances: ["physical"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_charge"], aiRules: [aiRule(90, [{ kind: "roundAtLeast", round: 2 }], "skill_enemy_charge", "frontFirstOpponent")] },
  { id: "enemy_sporeling", level: 8, stats: stats(450, 75, 22, 48, 300, 200), elementWeaknesses: ["fire"], elementResistances: ["poison"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_poison_hit"], aiRules: [aiRule(80, [{ kind: "always" }], "skill_enemy_poison_hit", "lowestHpOpponent")] },
  { id: "enemy_venom_spider", level: 8, stats: stats(425, 63, 23, 64, 300, 200), elementWeaknesses: ["frost"], elementResistances: ["poison"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_poison_double"], aiRules: [aiRule(80, [{ kind: "always" }], "skill_enemy_poison_double", "lowestHpOpponent")] },
  { id: "enemy_fungal_guardian", level: 8, stats: stats(1305, 61, 48, 37, 300, 200), elementWeaknesses: ["fire"], elementResistances: ["poison"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_guard_all"], aiRules: [aiRule(90, [{ kind: "anyAllyHpAtMostBps", valueBps: 6000 }], "skill_enemy_guard_all", "self")] },
  { id: "enemy_cave_bat", level: 13, stats: stats(637, 86, 34, 67, 500, 400), elementWeaknesses: ["lightning"], elementResistances: ["dark"], immunityTags: [], basicSkillId: "skill_enemy_basic_ranged", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_enemy_haste"], aiRules: [aiRule(80, [{ kind: "selfMissingStatus", statusId: "status_haste" }], "skill_enemy_haste", "self")] },
  { id: "enemy_ore_golem", level: 13, stats: stats(1956, 82, 69, 38, 500, 400), elementWeaknesses: ["lightning"], elementResistances: ["physical"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_stun_hit"], aiRules: [aiRule(80, [{ kind: "always" }], "skill_enemy_stun_hit", "frontFirstOpponent")] },
  { id: "enemy_bomb_goblin", level: 13, stats: stats(675, 102, 32, 50, 500, 400), elementWeaknesses: ["frost"], elementResistances: ["fire"], immunityTags: [], basicSkillId: "skill_enemy_basic_ranged", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_enemy_all_physical"], aiRules: [aiRule(70, [{ kind: "opponentCountAtLeast", count: 2 }], "skill_enemy_all_physical", "self")] },
  { id: "enemy_bog_leech", level: 18, stats: stats(1050, 84, 50, 49, 700, 600), elementWeaknesses: ["holy"], elementResistances: ["poison"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_self_heal"], aiRules: [aiRule(90, [{ kind: "selfHpAtMostBps", valueBps: 4500 }], "skill_enemy_self_heal", "self")] },
  { id: "enemy_mist_wraith", level: 18, stats: stats(1620, 157, 50, 54, 700, 600), elementWeaknesses: ["holy"], elementResistances: ["dark"], immunityTags: [], basicSkillId: "skill_enemy_basic_ranged", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_enemy_fear_all"], aiRules: [aiRule(85, [{ kind: "roundEquals", round: 1 }], "skill_enemy_fear_all", "self"), aiRule(80, [{ kind: "opponentsMissingStatusCountAtLeast", statusId: "status_fear", count: 2 }], "skill_enemy_fear_all", "self")] },
  { id: "enemy_ember_hound", level: 23, stats: stats(1755, 158, 71, 43, 900, 800), elementWeaknesses: ["frost"], elementResistances: ["fire"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_burn_hit"], aiRules: [aiRule(80, [{ kind: "always" }], "skill_enemy_burn_hit", "frontFirstOpponent")] },
  { id: "enemy_ash_cultist", level: 23, stats: stats(2106, 198, 64, 56, 900, 800), elementWeaknesses: ["holy"], elementResistances: ["fire"], immunityTags: [], basicSkillId: "skill_enemy_basic_ranged", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_enemy_burn_all"], aiRules: [aiRule(75, [{ kind: "opponentCountAtLeast", count: 2 }], "skill_enemy_burn_all", "self")] },
  { id: "enemy_abyss_mauler", level: 28, stats: stats(3888, 237, 108, 48, 1100, 1000), elementWeaknesses: ["holy"], elementResistances: ["dark"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_execute"], aiRules: [aiRule(95, [{ kind: "anyOpponentHpAtMostBps", valueBps: 3000 }], "skill_enemy_execute", "lowestHpOpponent")] },
  { id: "enemy_dread_eye", level: 28, stats: stats(1440, 206, 68, 58, 1100, 1000), elementWeaknesses: ["holy"], elementResistances: ["dark"], immunityTags: [], basicSkillId: "skill_enemy_basic_ranged", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_enemy_fear_hit"], aiRules: [aiRule(80, [{ kind: "always" }], "skill_enemy_fear_hit", "lowestHpOpponent")] },
  { id: "enemy_blood_ghoul", level: 33, stats: stats(1615, 215, 90, 82, 1300, 1200), elementWeaknesses: ["holy"], elementResistances: ["dark"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_bleed_double"], aiRules: [aiRule(80, [{ kind: "always" }], "skill_enemy_bleed_double", "frontFirstOpponent")] },
  { id: "enemy_crimson_acolyte", level: 33, stats: stats(3591, 196, 120, 59, 1300, 1200), elementWeaknesses: ["frost"], elementResistances: ["dark"], immunityTags: [], basicSkillId: "skill_enemy_basic_ranged", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_enemy_ally_heal"], aiRules: [aiRule(95, [{ kind: "anyAllyHpAtMostBps", valueBps: 5500 }], "skill_enemy_ally_heal", "lowestHpAlly")] },
  { id: "enemy_frost_warden", level: 38, stats: stats(5871, 256, 225, 50, 1500, 1400), elementWeaknesses: ["fire"], elementResistances: ["frost"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_frost_guard"], aiRules: [aiRule(90, [{ kind: "anyAllyHpAtMostBps", valueBps: 7000 }], "skill_enemy_frost_guard", "self")] },
  { id: "enemy_ice_revenant", level: 38, stats: stats(2025, 315, 104, 64, 1500, 1400), elementWeaknesses: ["fire"], elementResistances: ["frost"], immunityTags: [], basicSkillId: "skill_enemy_basic_ranged", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_enemy_freeze_hit"], aiRules: [aiRule(80, [{ kind: "always" }], "skill_enemy_freeze_hit", "lowestHpOpponent")] },
  { id: "enemy_void_spark", level: 43, stats: stats(2210, 320, 134, 90, 1700, 1600), elementWeaknesses: ["physical"], elementResistances: ["lightning"], immunityTags: [], basicSkillId: "skill_enemy_basic_ranged", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_enemy_shock_double"], aiRules: [aiRule(80, [{ kind: "always" }], "skill_enemy_shock_double", "randomValid")] },
  { id: "enemy_watcher_shard", level: 43, stats: stats(4212, 457, 151, 70, 1700, 1600), elementWeaknesses: ["dark"], elementResistances: ["lightning"], immunityTags: [], basicSkillId: "skill_enemy_basic_ranged", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_enemy_slow_all"], aiRules: [aiRule(90, [{ kind: "roundEquals", round: 1 }], "skill_enemy_slow_all", "self"), aiRule(80, [{ kind: "opponentsMissingStatusCountAtLeast", statusId: "status_slow", count: 2 }], "skill_enemy_slow_all", "self")] },
  { id: "enemy_throne_knight", level: 48, stats: stats(7830, 374, 330, 54, 2000, 1800), elementWeaknesses: ["holy"], elementResistances: ["dark"], immunityTags: [], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_enemy_counter_guard"], aiRules: [aiRule(90, [{ kind: "selfHpAtMostBps", valueBps: 7000 }, { kind: "selfMissingStatus", statusId: "status_shield" }], "skill_enemy_counter_guard", "self")] },
  { id: "enemy_abyss_herald", level: 48, stats: stats(2700, 460, 152, 70, 2000, 1800), elementWeaknesses: ["holy"], elementResistances: ["dark"], immunityTags: [], basicSkillId: "skill_enemy_basic_ranged", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_enemy_all_physical"], aiRules: [aiRule(70, [{ kind: "opponentCountAtLeast", count: 2 }], "skill_enemy_all_physical", "self")] },
  { id: "boss_horned_king", level: 5, stats: stats(2400, 62, 26, 42, 500, 1000), elementWeaknesses: ["fire"], elementResistances: [], immunityTags: ["stun"], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_boss_horned_charge", "skill_boss_horned_call", "skill_boss_enrage"], aiRules: [aiRule(120, [{ kind: "roundAtLeast", round: 12 }, { kind: "selfMissingStatus", statusId: "status_boss_enrage" }], "skill_boss_enrage", "self"), aiRule(100, [{ kind: "selfHpAtMostBps", valueBps: 5000 }, { kind: "selfMissingStatus", statusId: "status_boss_phase_2" }], "skill_boss_horned_call", "self"), aiRule(70, [{ kind: "always" }], "skill_boss_horned_charge", "frontFirstOpponent")] },
  { id: "boss_brood_spider", level: 10, stats: stats(4200, 88, 38, 52, 900, 1300), elementWeaknesses: ["fire"], elementResistances: ["poison"], immunityTags: ["poison"], basicSkillId: "skill_enemy_poison_hit", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_boss_brood_venom_web", "skill_boss_brood_hatch", "skill_boss_enrage"], aiRules: [aiRule(120, [{ kind: "roundAtLeast", round: 11 }, { kind: "selfMissingStatus", statusId: "status_boss_enrage" }], "skill_boss_enrage", "self"), aiRule(100, [{ kind: "selfHpAtMostBps", valueBps: 5000 }, { kind: "selfMissingStatus", statusId: "status_boss_phase_2" }], "skill_boss_brood_hatch", "self"), aiRule(75, [{ kind: "roundAtLeast", round: 2 }], "skill_boss_brood_venom_web", "self")] },
  { id: "boss_iron_devourer", level: 15, stats: stats(6200, 118, 65, 38, 900, 1600), elementWeaknesses: ["lightning"], elementResistances: ["physical"], immunityTags: ["stun"], basicSkillId: "skill_enemy_stun_hit", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_boss_iron_quake", "skill_boss_iron_overdrive", "skill_boss_enrage"], aiRules: [aiRule(120, [{ kind: "roundAtLeast", round: 12 }, { kind: "selfMissingStatus", statusId: "status_boss_enrage" }], "skill_boss_enrage", "self"), aiRule(100, [{ kind: "selfHpAtMostBps", valueBps: 5000 }, { kind: "selfMissingStatus", statusId: "status_boss_phase_2" }], "skill_boss_iron_overdrive", "self"), aiRule(75, [{ kind: "always" }], "skill_boss_iron_quake", "self")] },
  { id: "boss_bog_witch", level: 20, stats: stats(7800, 142, 64, 58, 1300, 1900), elementWeaknesses: ["holy"], elementResistances: ["dark"], immunityTags: ["poison"], basicSkillId: "skill_enemy_fear_hit", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_boss_witch_miasma", "skill_boss_witch_rebirth", "skill_boss_enrage"], aiRules: [aiRule(120, [{ kind: "roundAtLeast", round: 14 }, { kind: "selfMissingStatus", statusId: "status_boss_enrage" }], "skill_boss_enrage", "self"), aiRule(100, [{ kind: "selfHpAtMostBps", valueBps: 5000 }, { kind: "selfMissingStatus", statusId: "status_boss_phase_2" }], "skill_boss_witch_rebirth", "self"), aiRule(75, [{ kind: "roundAtLeast", round: 2 }], "skill_boss_witch_miasma", "self")] },
  { id: "boss_ember_guardian", level: 25, stats: stats(10500, 182, 92, 55, 1500, 2100), elementWeaknesses: ["frost"], elementResistances: ["fire"], immunityTags: ["burn"], basicSkillId: "skill_enemy_burn_hit", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_boss_ember_sweep", "skill_boss_ember_eruption", "skill_boss_enrage"], aiRules: [aiRule(120, [{ kind: "roundAtLeast", round: 11 }, { kind: "selfMissingStatus", statusId: "status_boss_enrage" }], "skill_boss_enrage", "self"), aiRule(100, [{ kind: "selfHpAtMostBps", valueBps: 5000 }, { kind: "selfMissingStatus", statusId: "status_boss_phase_2" }], "skill_boss_ember_eruption", "self"), aiRule(75, [{ kind: "always" }], "skill_boss_ember_sweep", "self")] },
  { id: "boss_abyss_butcher", level: 30, stats: stats(13000, 230, 116, 62, 1800, 2400), elementWeaknesses: ["holy"], elementResistances: ["dark"], immunityTags: ["fear"], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_boss_butcher_cleaver", "skill_boss_butcher_frenzy", "skill_boss_enrage"], aiRules: [aiRule(120, [{ kind: "roundAtLeast", round: 12 }, { kind: "selfMissingStatus", statusId: "status_boss_enrage" }], "skill_boss_enrage", "self"), aiRule(100, [{ kind: "selfHpAtMostBps", valueBps: 5000 }, { kind: "selfMissingStatus", statusId: "status_boss_phase_2" }], "skill_boss_butcher_frenzy", "self"), aiRule(90, [{ kind: "anyOpponentHpAtMostBps", valueBps: 3000 }], "skill_boss_butcher_cleaver", "lowestHpOpponent"), aiRule(65, [{ kind: "always" }], "skill_boss_butcher_cleaver", "lowestHpOpponent")] },
  { id: "boss_crimson_knight", level: 35, stats: stats(14500, 285, 132, 72, 2000, 2600), elementWeaknesses: ["frost"], elementResistances: ["dark"], immunityTags: ["bleed"], basicSkillId: "skill_enemy_bleed_double", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_boss_crimson_flurry", "skill_boss_crimson_bloodmoon", "skill_boss_enrage"], aiRules: [aiRule(120, [{ kind: "roundAtLeast", round: 13 }, { kind: "selfMissingStatus", statusId: "status_boss_enrage" }], "skill_boss_enrage", "self"), aiRule(100, [{ kind: "selfHpAtMostBps", valueBps: 5000 }, { kind: "selfMissingStatus", statusId: "status_boss_phase_2" }], "skill_boss_crimson_bloodmoon", "self"), aiRule(75, [{ kind: "always" }], "skill_boss_crimson_flurry", "frontFirstOpponent")] },
  { id: "boss_pale_jailer", level: 40, stats: stats(15500, 345, 185, 58, 2200, 2900), elementWeaknesses: ["fire"], elementResistances: ["frost"], immunityTags: ["freeze"], basicSkillId: "skill_enemy_freeze_hit", basicTargetStrategy: "lowestHpOpponent", skillIds: ["skill_boss_jailer_prison", "skill_boss_jailer_whitewall", "skill_boss_enrage"], aiRules: [aiRule(120, [{ kind: "roundAtLeast", round: 14 }, { kind: "selfMissingStatus", statusId: "status_boss_enrage" }], "skill_boss_enrage", "self"), aiRule(100, [{ kind: "selfHpAtMostBps", valueBps: 5000 }, { kind: "selfMissingStatus", statusId: "status_boss_phase_2" }], "skill_boss_jailer_whitewall", "self"), aiRule(75, [{ kind: "roundAtLeast", round: 2 }], "skill_boss_jailer_prison", "self")] },
  { id: "boss_thousand_eye", level: 45, stats: stats(18000, 420, 190, 78, 2500, 3100), elementWeaknesses: ["dark"], elementResistances: ["lightning"], immunityTags: ["stun"], basicSkillId: "skill_enemy_shock_double", basicTargetStrategy: "randomValid", skillIds: ["skill_boss_eye_chain", "skill_boss_eye_rewrite", "skill_boss_enrage"], aiRules: [aiRule(120, [{ kind: "roundAtLeast", round: 11 }, { kind: "selfMissingStatus", statusId: "status_boss_enrage" }], "skill_boss_enrage", "self"), aiRule(100, [{ kind: "selfHpAtMostBps", valueBps: 5000 }, { kind: "selfMissingStatus", statusId: "status_boss_phase_2" }], "skill_boss_eye_rewrite", "self"), aiRule(75, [{ kind: "always" }], "skill_boss_eye_chain", "randomValid")] },
  { id: "boss_abyss_king", level: 50, stats: stats(19000, 510, 240, 75, 2800, 3500), elementWeaknesses: ["holy"], elementResistances: ["dark"], immunityTags: ["stun", "freeze", "fear"], basicSkillId: "skill_enemy_basic_physical", basicTargetStrategy: "frontFirstOpponent", skillIds: ["skill_boss_king_dark_wave", "skill_boss_king_phase_two", "skill_boss_king_phase_three", "skill_boss_king_annihilation", "skill_boss_enrage"], aiRules: [aiRule(120, [{ kind: "roundAtLeast", round: 14 }, { kind: "selfMissingStatus", statusId: "status_boss_enrage" }], "skill_boss_enrage", "self"), aiRule(110, [{ kind: "selfHpAtMostBps", valueBps: 3500 }, { kind: "selfHasStatus", statusId: "status_boss_phase_2" }, { kind: "selfMissingStatus", statusId: "status_boss_phase_3" }], "skill_boss_king_phase_three", "self"), aiRule(100, [{ kind: "selfHpAtMostBps", valueBps: 7000 }, { kind: "selfMissingStatus", statusId: "status_boss_phase_2" }], "skill_boss_king_phase_two", "self"), aiRule(90, [{ kind: "selfHasStatus", statusId: "status_boss_phase_3" }], "skill_boss_king_annihilation", "self"), aiRule(70, [{ kind: "always" }], "skill_boss_king_dark_wave", "self")] },
];

describe("敌人内容数值 golden", () => {
  it("35 个普通/精英与 Boss 的等级、面板、元素、免疫、基础技能和 AI 全量固定", () => {
    expect(ENEMY_DEFINITIONS).toHaveLength(35);
    const actualById = new Map(ENEMY_DEFINITIONS.map((enemy) => [enemy.id, projection(enemy)]));
    expect([...actualById.keys()].sort()).toEqual(expected.map((enemy) => enemy.id).sort());
    expect([...actualById.values()].sort((left, right) => left.id.localeCompare(right.id)))
      .toEqual([...expected].sort((left, right) => left.id.localeCompare(right.id)));
  });
});
